export const coursesData = [
  {
    id: 1,
    title: "Thai Wok Mastery",
    chef: "Ethan Winters",
    price: 650,
    level: "Intermediate",
    available: true,
  },
  {
    id: 2,
    title: "Spices of India",
    chef: "Grace Ashcroft",
    price: 820,
    level: "Beginner",
    available: true,
  },
  {
    id: 3,
    title: "Japanese Izakaya Favorites",
    chef: "Chef Leon S. Kennedy",
    price: 1200,
    level: "Advanced",
    available: false,
  },
  {
    id: 4,
    title: "Moroccan Tagine Traditions",
    chef: "Chef Zeno",
    price: 460,
    level: "Beginner",
    available: true,
  },
  {
    id: 5,
    title: "Mexican Street Food",
    chef: "Carlos Oliviera",
    price: 1050,
    level: "Intermediate",
    available: false,
  },
  {
    id: 6,
    title: "Traditional Korean Confectionery",
    chef: "Chris Redfield",
    price: 910,
    level: "Advanced",
    available: true,
  },
];
